modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/TeamDiopside/InfinityButtons-1.19/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://teamdiopside.nl/projects/infinitybuttons"
logoFile="icon.png"
authors="LarsMans"
credits="curryducker, haoooo_, NeoForge 1.21.1 port"
description='''${mod_description}'''

[[mixins]]
config="infinitybuttons.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
